In [16]:
import cv2 as cv
import numpy as np
from skimage.data import coins
import napari
import skimage.morphology
import skimage.segmentation
%gui qt

ImportError: cannot import name 'nbscreenshot'

In [2]:
img = coins()

In [3]:
v= napari.Viewer()

In [4]:
mask = img >120
mask = skimage.morphology.remove_small_holes(mask, 100)
mask = skimage.morphology.remove_small_objects(mask, 100)
mask = (mask*255).astype(np.uint8) # for opencv compatibility

In [5]:
v.add_image(mask)

<Image layer 'mask' at 0x1bede9a2c50>

In [6]:
 contours, contour_mat = cv.findContours(mask, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)

In [13]:
 # Find the rotated rectangles and ellipses for each contour
minRect = [None]*len(contours)
minEllipse = [None]*len(contours)
for i, c in enumerate(contours):
    minRect[i] = cv.minAreaRect(c)

# Draw contours + rotated rects + ellipses

drawing = np.zeros((mask.shape[0], mask.shape[1], 3), dtype=np.uint8)

for i, c in enumerate(contours):
    color = (127,127,1)
    # contour
    #cv.drawContours(drawing, contours, i, color)
    # rotated rectangle
    box = cv.boxPoints(minRect[i])
    box = np.intp(box) #np.intp: Integer used for indexing (same as C ssize_t; normally either int32 or int64)
    print(box)
    cv.drawContours(drawing, [box], 0, color)

[[336 288]
 [336 248]
 [380 248]
 [380 288]]
[[ 93 286]
 [ 93 246]
 [135 246]
 [135 286]]
[[235 294]
 [212 256]
 [252 231]
 [276 270]]
[[276 287]
 [276 240]
 [325 240]
 [325 287]]
[[147 286]
 [147 237]
 [200 237]
 [200 286]]
[[ 33 296]
 [  9 247]
 [ 59 223]
 [ 83 271]]
[[ 48 286]
 [ 40 273]
 [ 68 255]
 [ 76 268]]
[[ 40 274]
 [ 29 263]
 [ 38 254]
 [ 49 265]]
[[145 222]
 [129 189]
 [162 172]
 [179 205]]
[[ 26 216]
 [ 26 179]
 [ 62 179]
 [ 62 216]]
[[ 80 216]
 [ 80 175]
 [123 175]
 [123 216]]
[[288 219]
 [246 205]
 [259 166]
 [301 180]]
[[196 221]
 [183 178]
 [227 164]
 [240 208]]
[[340 229]
 [305 177]
 [356 143]
 [390 195]]
[[134 144]
 [134 110]
 [173 110]
 [173 144]]
[[ 93 150]
 [ 77 118]
 [111 101]
 [127 133]]
[[336 151]
 [310 125]
 [337  98]
 [363 124]]
[[212 149]
 [178 132]
 [196  97]
 [230 114]]
[[ 25 144]
 [ 25 104]
 [ 66 104]
 [ 66 144]]
[[288 147]
 [240 135]
 [252  89]
 [300 101]]
[[ 81  73]
 [ 81  39]
 [119  39]
 [119  73]]
[[282  78]
 [249  57]
 [270  25]
 [303  47]]
[[53 82]
 

In [8]:
drawing.shape

(303, 384, 3)

In [9]:
v.add_image(drawing)

<Image layer 'drawing' at 0x1bef5620a58>

In [12]:
v.add_labels(skimage.morphology.label(mask>0))

<Labels layer 'Labels' at 0x1bef800c978>